"""add voted column to users

Revision ID: bd3389338eb1
Revises: d46fa35b9465
Create Date: 2020-06-07 17:09:20.658396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3389338eb1'
down_revision = 'd46fa35b9465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('voted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voted')
    # ### end Alembic commands ###
